### ISSUE TITLE
Review SRS Document - Secondary Reviewer

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/3D-Image-Reconstruction-Segmentation#6]
Hi Waqar,

Please review my initial [SRS](https://github.com/NadaElmasry/3D-Image-Reconstruction-Segmentation/blob/main/docs/SRS/SRS.pdf) document. 

Thank you!

**Comment by WaqarAwan376** [comment]
**Possible Improvements:**
- The document specifies the NIfTI format for input data. Since we’re working with brain images, maybe specifying what makes for good quality data or any preprocessing steps needed, and what would be the effect of preprocessing on the image/data would help avoid any confusion later on. 
- While non-functional requirements like usability and maintainability are mentioned, expanding on performance metrics, and scalability could provide a more better view of system expectations.
- Given the sensitive nature of medical data, including specific measures for data security and patient privacy would be crucial.
- Clarification on the level of expertise required for users, such as specific software skills or familiarity with neuroimaging concepts, could help understand the system more effectively to the intended audience.

**Good Points:**
- The document thoroughly covers every aspect of the system, from general descriptions to specific models and requirements.
- The goal statements are quite well-defined, offering clear targets for the project's outcomes.
- The purpose and scope sections set clear expectations for the reader and effectively introduce the project’s aims.
- The problem description section outlines the challenges and objectives, guiding the focus of the software development.

**Comment by smiths** [comment]
@WaqarAwan376 in the future please create separate issues for each of your points.
